### ISSUE TITLE
Set action's config from *.yaml file

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#111]
It should be possible to set action's config from `*.yaml` file.

Generally, everything that possible to do with backend app should be possible to do with deploy files.

**Comment by zaniar** [comment]
My current case is I want to use SQL-Table as action. But apparently there is no way to pass table name to the action.

**Comment by k42b3** [comment]
> Generally, everything that possible to do with backend app should be possible to do with deploy files.

Yes, this is the goal of the deploy command. So it is possible to define an action, unfortunately this feature is not well documented but you could define an action in the `.fusio.yml` with i.e.:

```yaml
action:
  Test-Action:
    class: Fusio\Adapter\Sql\Action\SqlTable
    config:
      connection: "connection-1"
      table: "acme_table"
```

The config contains the same values which you also provide through the backend. Please let me know whether this works for your case.
