### ISSUE TITLE
Missing deploy features

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#112]
Related to #111 

I will try to list what currently missing in deploy.

- [ ] set action's config (#111)
- [ ] deploy action that not tied to a route
- [ ] deploy cronjob
- [ ] deploy app
- [ ] deploy user
- [ ] deploy rate

**Comment by k42b3** [comment]
Yes this is a good idea. So actions and cronjobs are already possible i.e.:

```yaml
action:
  Test-Action:
    class: Fusio\Adapter\Util\Action\UtilStaticResponse
    config:
      response: '{"foo": "bar"}'
cronjob:
  New-Cron:
    cron: "15 * * * *"
    action: Test-Action
```

the other entities are missing. I think adding rate is probably the most important feature.
