### ISSUE TITLE
Set default rate limit during deploy

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio#156]
It would be nice, if we could overwrite the default rate limit in .fusio.yaml (or configuration.php). 
The set values should override the [default values](https://github.com/apioo/fusio-impl/blob/0cf3f3c0a2541a34aa380952f410ed7b9eae0c6d/src/Database/Version/Version307.php#L515) during `fusio deploy`

**Comment by chriskapp** [comment]
Hi, so in general it is possible to add or update new rate limits through the `.fusio.yml` file i.e.:

```yaml
rate:
  Default-Anonymous:
    priority: 8
    rateLimit: 180
    timespan: "PT1H"
    allocation:
      - authenticated: true
        parameters: "level=anonymous"
  Default:
    priority: 2
    rateLimit: 1400
    timespan: "PT1H"
    allocation:
      - authenticated: true
        parameters: "level=default"
```

but it is only possible to add or edit existing entries, it is not possible to delete an entry.
