### ISSUE TITLE
How to get Config

### ISSUE THREAD

**Issue by subangkit** [apioo/fusio#46]
Hi, can u explain how to get configuration form DB fusio and configuration.php from Action?

**Comment by k42b3** [comment]
Hi, so inside an action it is not recommended to access the `configuration.php` values. This is a design decision because these values are only for the Fusio system. In an action you can access a connection through i.e. `$connector->getConnection('New-Connection');`. You can configure this connection inside your `.fusio.yml` file i.e.:

```
connection:
  New-Connection:
    class: Fusio\Adapter\Sql\Connection\Sql
    config:
      type: "pdo_mysql"
      host: "host"
      username: "username"
      password: "password"
      database: "database"
```

So you should not configure any database connections inside an action. Or is there any specific use case why you want to access the `configuration.php` inside an action? But if you really want to access those values nobody can stop you to simply include the config in your action, since it is also only a simple php file i.e.:

```
$config = include __DIR__ . '/../../configuration.php';
```

If you need to use the database connection which you have provided at the `psx_connection` key you can also use the `Fusio\Impl\Connection\System` connection i.e.:

```
connection:
  System-Connection:
    class: Fusio\Impl\Connection\System
```

But please dont use the system connection for your application since the migration script would delete all other tables which are not defined in your schema. It is recommended to setup two databases one for fusio and the other for your application.
