### ISSUE TITLE
Fusion installation script failed

### ISSUE THREAD

**Issue by GMKostov** [apioo/fusio#529]
I'm trying to install Fusio (v4.0.3 downloaded from GitHub). I use IIS on Windows Server 2002. I installed the latest PHP (8.0.3) and MySQL (8.0.32) and activated PDO_MySQL. I created database named "fusio" in MySQL and an user "fusio" with full access to the database "fusio". The installation script "public/install.php" fails with the fallowing error:

```
[An error occurred on installation:
[notice] Migrating up to Fusio\Impl\Migrations\Version20230922194158
[error] Migration Fusio\Impl\Migrations\Version20230508210151 failed during Execution. Error: "The column "operation_id" on table "fusio_log" already exists."

In ColumnAlreadyExists.php line 16:
                                                                  
  The column "operation_id" on table "fusio_log" already exists.  
                                                                  

migrations:migrate [--write-sql [WRITE-SQL]] [--dry-run] [--query-time] [--allow-no-migration] [--all-or-nothing [ALL-OR-NOTHING]] [--configuration CONFIGURATION] [--em EM] [--conn CONN] [--] [<version>]](url)
```

What could be the problem?

**Comment by GMKostov** [comment]
Well. I decided that too much things named "fusio" may be a problem, so I deleted droped database "fusio" and created a new one named "fusiodb". The db user account I left as is - "fusio". Now the script succeeded up to step 3, where I got this error:

```
Could not install backend app, you can install the backend app later on using the command bin/fusio marketplace:install fusio
In StreamHandler.php line 72:
                                                                             
  Connection refused for URI https://www.fusio-project.org/marketplace.yaml  
                                                                             

In StreamHandler.php line 329:
                                                                             
  Connection refused for URI https://www.fusio-project.org/marketplace.yaml  
                                                                             

marketplace:install [-d|--disable_ssl_verify] [-x|--disable_env] [--] <name>

```

I have no problem to open that URL from a browser on the server and it shows this info:

```
fusio:
    version: 3.0.8
    downloadUrl: 'https://github.com/apioo/fusio-apps-backend/releases/download/v3.0.8/fusio.zip'
    sha1Hash: db90623e08a225188dd5956883ea0589ef76797e
    description: 'The backend app is the official app to develop, configure and maintain your API.'
    screenshot: 'https://www.fusio-project.org/media/apps/backend.png'
    website: 'https://github.com/apioo/fusio-apps-backend'
developer:
    version: 3.0.4
    ...
```

I believe this is and optional step, and I hope I will be able to test Fusio finally :)
